name: Linux Build

on: push

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: 31fc1481f529ba1a72a8a6bc62dc488b84fc2cdb
    - name: Install dependencies
      run: |
        sudo apt-get install gcc-aarch64-linux-gnu build-essential
    - name: Build C Code
      run: |
        find . -name Makefile | while read makefile; do
          dir=$(dirname "$makefile")
          dir2="./exercises/lesson02/2/szediwy" 
          echo "Entering directory: $dir"
          if diff -qr "$dir" "$dir2" > /dev/null; then
            echo "Does not compile in this dir."
          else
            (cd "$dir" && make)
          fi
          
        done
